<a href="https://colab.research.google.com/github/hbisgin/DeepLearning/blob/main/DL_14_5_RNN_OutputDimensions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn

# ============================================
# 1. Define dimensions
# ============================================

B = 2   # batch size (2 sequences)
T = 3   # sequence length
D = 4   # input size
H = 5   # hidden size

# ============================================
# 2. Create dummy input
# ============================================

x = torch.randn(B, T, D)
print(x)

print("Input shape (B, T, D):", x.shape)


# ============================================
# 3. Define RNN
# ============================================

rnn = nn.RNN(input_size=D, hidden_size=H, batch_first=True)


# ============================================
# 4. Forward pass
# ============================================

output, h_n = rnn(x)

print("\nOutput shape (B, T, H):", output.shape)
print("Final hidden shape (1, B, H):", h_n.shape)
print(output)
print(h_n)

tensor([[[-0.3804,  0.7170,  0.6588, -1.1038],
         [-2.0738,  0.6382, -0.2718,  1.1210],
         [-0.2460, -1.3653, -0.9614,  0.4544]],

        [[ 0.4605, -0.2446, -0.1029, -1.6656],
         [-1.3838, -1.3665,  0.0968, -0.4819],
         [-0.5961, -0.0736,  0.1704, -0.1204]]])
Input shape (B, T, D): torch.Size([2, 3, 4])

Output shape (B, T, H): torch.Size([2, 3, 5])
Final hidden shape (1, B, H): torch.Size([1, 2, 5])
tensor([[[ 0.6821,  0.3157,  0.7216,  0.4657, -0.5348],
         [ 0.8845,  0.8074, -0.4312,  0.6413, -0.7742],
         [-0.1387, -0.2055,  0.5993, -0.8614, -0.8474]],

        [[ 0.1230, -0.6417,  0.9016, -0.4747, -0.4972],
         [ 0.7971, -0.5655,  0.8652, -0.2661, -0.8063],
         [ 0.5779, -0.3929,  0.6334, -0.2099, -0.7555]]],
       grad_fn=<TransposeBackward1>)
tensor([[[-0.1387, -0.2055,  0.5993, -0.8614, -0.8474],
         [ 0.5779, -0.3929,  0.6334, -0.2099, -0.7555]]],
       grad_fn=<StackBackward0>)


In [3]:
W_input = rnn.weight_ih_l0   # (H, D)
W_hidden = rnn.weight_hh_l0  # (H, H)

print(W_input)
print(W_hidden)

Parameter containing:
tensor([[-0.3631,  0.0067,  0.3955,  0.1716],
        [-0.3712,  0.4087,  0.2276,  0.3728],
        [ 0.1698, -0.4076,  0.2566, -0.4107],
        [-0.3038,  0.4346,  0.3237,  0.1795],
        [ 0.2264,  0.0583,  0.1279, -0.0257]], requires_grad=True)
Parameter containing:
tensor([[-0.2572, -0.0930,  0.2908,  0.2232,  0.3251],
        [-0.3216,  0.2352, -0.4399,  0.0484, -0.0353],
        [-0.1695, -0.0950,  0.0454,  0.1054, -0.1859],
        [-0.4389, -0.1187,  0.0976,  0.1812,  0.2623],
        [-0.0929, -0.0171,  0.3330,  0.3796,  0.4079]], requires_grad=True)
