<a href="https://colab.research.google.com/github/hbisgin/DeepLearning/blob/main/DL_14_5_RNN_OutputDimensions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import torch.nn as nn


# 1. Define dimensions


B = 2   # batch size (2 sequences)
T = 3   # sequence length
D = 4   # input size
H = 5   # hidden size


# 2. Create dummy input


x = torch.randn(B, T, D)
print(x)

print("Input shape (B, T, D):", x.shape)




tensor([[[ 0.6999,  0.7890, -0.2129,  0.1030],
         [ 0.8325,  0.2183,  0.7495, -0.8872],
         [-0.8118,  0.7112, -0.4284,  0.4662]],

        [[ 0.1988, -0.9085, -0.0111, -0.8259],
         [-0.3262, -1.6014,  0.5444, -0.3876],
         [-0.9810, -1.0242, -1.3538,  0.1908]]])
Input shape (B, T, D): torch.Size([2, 3, 4])


Define RNN with one layer, unidirectional



In [14]:
rnn = nn.RNN(input_size=D, hidden_size=H, batch_first=True)


#Forward pass

output, h_n = rnn(x)

print("\nOutput shape (B, T, H):", output.shape)
print("Final hidden shape (num_layers * num_directions, B, H) (1, B, H):", h_n.shape)
print(output)
print(h_n)


Output shape (B, T, H): torch.Size([2, 3, 5])
Final hidden shape (num_layers * num_directions, B, H) (1, B, H): torch.Size([1, 2, 5])
tensor([[[-0.3339, -0.5272, -0.7267, -0.5543,  0.6215],
         [-0.1755, -0.3723, -0.6615, -0.6835,  0.8682],
         [-0.2396, -0.4952, -0.4361, -0.7716,  0.8410]],

        [[-0.0801, -0.0519, -0.5274, -0.5272,  0.5844],
         [ 0.3737,  0.1424, -0.0287, -0.6958,  0.7050],
         [ 0.1202,  0.0743, -0.4892, -0.7309,  0.6857]]],
       grad_fn=<TransposeBackward1>)
tensor([[[-0.2396, -0.4952, -0.4361, -0.7716,  0.8410],
         [ 0.1202,  0.0743, -0.4892, -0.7309,  0.6857]]],
       grad_fn=<StackBackward0>)


Define RNN with one layer, bidirectional


In [13]:
rnn = nn.RNN(input_size=D, hidden_size=H, batch_first=True, num_layers=1, bidirectional=True)

#Forward pass

output, h_n = rnn(x)

print("\nOutput shape (B, T, 2*H):", output.shape)
print("Final hidden shape (num_layers * num_directions, B, H) (2, B, H):", h_n.shape)
print(output)
print(h_n)




Output shape (B, T, 2*H): torch.Size([2, 3, 10])
Final hidden shape (num_layers * num_directions, B, H) (2, B, H): torch.Size([2, 2, 5])
tensor([[[-0.4971, -0.1338,  0.3876, -0.1277, -0.0629, -0.4819, -0.3176,
          -0.3368,  0.1062,  0.5322],
         [-0.2719, -0.3752, -0.1728,  0.0759,  0.2647, -0.4183, -0.1312,
          -0.4082,  0.8512,  0.6894],
         [-0.7792,  0.6495,  0.3066,  0.2764, -0.5273, -0.6900, -0.0957,
          -0.3815, -0.2279,  0.1518]],

        [[-0.5080,  0.2774, -0.3021, -0.0164,  0.5356, -0.1389, -0.5342,
           0.7501,  0.4988,  0.7893],
         [-0.6390,  0.5804, -0.6487, -0.2260,  0.7305, -0.3139, -0.3613,
           0.7216,  0.5718,  0.5352],
         [-0.8298,  0.8318, -0.1300,  0.3648,  0.3211, -0.1770, -0.2953,
           0.5107,  0.2149,  0.3159]]], grad_fn=<TransposeBackward1>)
tensor([[[-0.7792,  0.6495,  0.3066,  0.2764, -0.5273],
         [-0.8298,  0.8318, -0.1300,  0.3648,  0.3211]],

        [[-0.4819, -0.3176, -0.3368,  0.1062,  0

Define RNN with two layers, bidirectional


In [12]:
rnn = nn.RNN(input_size=D, hidden_size=H, batch_first=True, num_layers=2, bidirectional=True)

#Forward pass

output, h_n = rnn(x)

print("\nOutput shape (B, T, 2*H):", output.shape)
print("Final hidden shape (num_layers * num_directions, B, H) (4, B, H):", h_n.shape)
print(output)
print(h_n)


Output shape (B, T, 2*H): torch.Size([2, 3, 10])
Final hidden shape (num_layers * num_directions, B, H) (4, B, H): torch.Size([4, 2, 5])
tensor([[[ 0.1824,  0.1772, -0.5272,  0.6739,  0.2017, -0.4279,  0.1429,
          -0.2608, -0.2322, -0.0275],
         [ 0.3606,  0.6331, -0.5224,  0.3454, -0.2028, -0.0577, -0.3287,
          -0.6036, -0.1402, -0.5118],
         [-0.0750,  0.4231, -0.6265,  0.3987,  0.1513, -0.5605,  0.2576,
          -0.2509,  0.3070,  0.0177]],

        [[ 0.4388,  0.3926,  0.0339,  0.2562,  0.1662, -0.2626, -0.0738,
          -0.1488,  0.1879, -0.3130],
         [ 0.3634,  0.6401, -0.2109,  0.1228,  0.2756, -0.0170, -0.0465,
          -0.4205,  0.5348, -0.2630],
         [-0.0405,  0.3162,  0.0535,  0.2822,  0.5337, -0.4317,  0.4451,
           0.4163,  0.5265, -0.1559]]], grad_fn=<TransposeBackward1>)
tensor([[[ 0.0952, -0.2961,  0.6732,  0.2602,  0.9481],
         [-0.4129, -0.4473,  0.5440, -0.3076,  0.6547]],

        [[ 0.3944,  0.4057,  0.2289, -0.7288,  0

In [2]:
W_input = rnn.weight_ih_l0   # (H, D)
W_hidden = rnn.weight_hh_l0  # (H, H)

print(W_input)
print(W_hidden)

Parameter containing:
tensor([[-0.2653, -0.0815, -0.2893, -0.2166],
        [-0.1704,  0.2628, -0.2658,  0.2191],
        [ 0.1037, -0.1475, -0.4017,  0.4443],
        [ 0.0456, -0.1962,  0.4121, -0.0384],
        [ 0.3723,  0.3114, -0.0556,  0.0308]], requires_grad=True)
Parameter containing:
tensor([[-0.4416, -0.1389, -0.0590, -0.2005, -0.3832],
        [-0.4116, -0.2475, -0.3861,  0.3446,  0.2971],
        [ 0.1691, -0.2499, -0.0151,  0.0067,  0.2051],
        [-0.0275,  0.0398,  0.3349,  0.3142,  0.1524],
        [-0.1051, -0.3859, -0.0552,  0.2607, -0.2496]], requires_grad=True)
