<a href="https://colab.research.google.com/github/hbisgin/DeepLearning/blob/main/DL_12_CNNwLinear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import torch.nn as nn

# signal
x = torch.tensor([[1.,2.,3.,4.,5.]]).unsqueeze(0)
# shape = (batch, channels, length)
#becomes (1,1,5)

# convolution
conv = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, bias=True)

# linear layer
linear = nn.Linear(3,1)

# copy weights so they match
linear.weight.data = conv.weight.data.view(1,3)
linear.bias.data = conv.bias.data

# convolution output
y_conv = conv(x)

# create sliding windows manually
windows = x.unfold(dimension=2, size=3, step=1) #slide a window of size 3 along dimension 2 move 1 step each time
print(windows)
windows = windows.squeeze(0).squeeze(0)
print(windows)

# apply linear layer to each window
y_linear = linear(windows)

print("Conv output:")
print(y_conv.squeeze())

print("Linear over windows:")
print(y_linear.squeeze())


tensor([[[[1., 2., 3.],
          [2., 3., 4.],
          [3., 4., 5.]]]])
tensor([[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.]])
Conv output:
tensor([1.7784, 2.2690, 2.7596], grad_fn=<SqueezeBackward0>)
Linear over windows:
tensor([1.7784, 2.2690, 2.7596], grad_fn=<SqueezeBackward0>)
